# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0

jobs:
  build_backend:
    working_directory: ~/majorproject-2-thurs-18-30-2/BackEnd

    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk


    environment:
      ECR_REPOSITORY_NAME: agme-backend
      FULL_IMAGE_NAME: 939196155225.dkr.ecr.us-east-1.amazonaws.com/agme-backend:latest

    steps:
      - checkout:
          path: ~/majorproject-2-thurs-18-30-2
      - setup_remote_docker
      #       - run:
      #           name: Setup common environment variables
      #           command: |
      #             echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
      #             echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest"' >> $BASH_ENV


      # Download and cache dependencies
      - restore_cache:
          keys:
            - backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: backend-{{ checksum "pom.xml" }}
      # run tests!
      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/backend-0.0.1.jar

      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Build image
          command: |
            docker build -t $ECR_REPOSITORY_NAME .
      - run:
          name: Push image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 939196155225.dkr.ecr.us-east-1.amazonaws.com/agme-backend:latest
            docker tag ${ECR_REPOSITORY_NAME}:latest 939196155225.dkr.ecr.us-east-1.amazonaws.com/agme-backend:latest
            docker push $FULL_IMAGE_NAME
  #FrontEnd
  build_frontend:
    working_directory: ~/majorproject-2-thurs-18-30-2/FrontEnd/frontend

    docker:
      - image: circleci/node:7.10

    environment:
      ECR_REPOSITORY_NAME: agme-frontend
      FULL_IMAGE_NAME: 939196155225.dkr.ecr.us-east-1.amazonaws.com/agme-frontend:latest

    steps:
      - checkout:
          path: ~/majorproject-2-thurs-18-30-2
      - setup_remote_docker

      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Build image
          command: |
            docker build -t $ECR_REPOSITORY_NAME .
      - run:
          name: Push image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 939196155225.dkr.ecr.us-east-1.amazonaws.com/agme-backend:latest
            docker tag ${ECR_REPOSITORY_NAME}:latest 939196155225.dkr.ecr.us-east-1.amazonaws.com/agme-backend:latest
            docker push $FULL_IMAGE_NAME

workflows:
  build-deploy-qa:
    jobs:
      - build_backend:
          filters:
            branches:
              only: master
      - build_frontend:
          filters:
            branches:
              only: master